run:
  timeout: 5m
  issues-exit-code: 1
linters:
  enable:
    - errcheck
    - gofmt
    - govet
    - ineffassign
    - staticcheck
    - revive
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
